remote_theme: pmarsceill/just-the-docs
# theme: just-the-docs

# Site Settings
title                    : "helpful dev feeds"
#title_separator          : "-"
name                     : "Jeong-Uk Park"
description              : "Helpful dev feeds"
url                      : "https://jeongph.github.io/helpful-feeds"
baseurl                  : "/"
repository               : "https://github.com/jeongph/helpful-feeds"
